#!/bin/bash
if [ -z "$PYFILE" ]; then
    echo "Error: Environment variable \$PYFILE not set."
    exit 1
fi

output_filename="${PYFILE}c"

python -m py_compile "$PYFILE"

if [ -f "$output_filename" ]; then
    echo "Compilation successful. Compiled file: $output_filename"
    exit 0
else
    echo "Compilation failed."
    exit 1
fi
